---
title: "Function reference"
aliases:
  - /_qrtdown/reference.html
---

All functions and classes exported by ti.

## All functions

<dl class="qrtdown-reference-index">
<dt><code><a href="abc.qmd">abc()</a></code></dt>
<dd>ABC classification function</dd>
<dt><code><a href="atd.qmd">atd()</a></code></dt>
<dd>All period-to-date</dd>
<dt><code><a href="augment_standard_calendar.qmd">augment_standard_calendar()</a></code></dt>
<dd>Add Comprehensive Date-Based Attributes to a DBI  lazy frame or tibble object</dd>
<dt><code><a href="calculate.qmd">calculate()</a></code></dt>
<dd>Execute time-intelligence or segments class objects to return the underlying transformed table</dd>
<dt><code><a href="cohort.qmd">cohort()</a></code></dt>
<dd>Cohort Analysis</dd>
<dt><code><a href="dod.qmd">dod()</a></code></dt>
<dd>Current period day over previous period day</dd>
<dt><code><a href="mom.qmd">mom()</a></code></dt>
<dd>Current full period month over previous full period month</dd>
<dt><code><a href="momtd.qmd">momtd()</a></code></dt>
<dd>Current period month to date compared to previous period month-to-date</dd>
<dt><code><a href="mtd.qmd">mtd()</a></code></dt>
<dd>Current period month-to-date</dd>
<dt><code><a href="mtdopm.qmd">mtdopm()</a></code></dt>
<dd>Current month-to-date over full previous period month</dd>
<dt><code><a href="pmtd.qmd">pmtd()</a></code></dt>
<dd>Previous period month-to-date</dd>
<dt><code><a href="pqtd.qmd">pqtd()</a></code></dt>
<dd>Prior period quarter-to-date</dd>
<dt><code><a href="pwtd.qmd">pwtd()</a></code></dt>
<dd>Previous period week-to-date</dd>
<dt><code><a href="pytd.qmd">pytd()</a></code></dt>
<dd>Previous period year-to-date</dd>
<dt><code><a href="qoq.qmd">qoq()</a></code></dt>
<dd>Current full period quarter over previous full period quarter</dd>
<dt><code><a href="qoqtd.qmd">qoqtd()</a></code></dt>
<dd>Current period quarter-to-date compared to previous period quarter-to-date</dd>
<dt><code><a href="qtd.qmd">qtd()</a></code></dt>
<dd>Current period quarter-to-date</dd>
<dt><code><a href="qtdopq.qmd">qtdopq()</a></code></dt>
<dd>Current period quarter-to-date over previous period quarter</dd>
<dt><code><a href="wow.qmd">wow()</a></code></dt>
<dd>Current full period week over full previous period week</dd>
<dt><code><a href="wowtd.qmd">wowtd()</a></code></dt>
<dd>Current period Week-to-date over previous period week-to-date</dd>
<dt><code><a href="wtd.qmd">wtd()</a></code></dt>
<dd>Current period week-to-date</dd>
<dt><code><a href="wtdopw.qmd">wtdopw()</a></code></dt>
<dd>Current period week-to-date over full previous period week</dd>
<dt><code><a href="yoy.qmd">yoy()</a></code></dt>
<dd>Current full period year over previous full period year</dd>
<dt><code><a href="yoytd.qmd">yoytd()</a></code></dt>
<dd>Current period year-to-date compared to previous period year-to-date</dd>
<dt><code><a href="ytd.qmd">ytd()</a></code></dt>
<dd>Current period year-to-date</dd>
<dt><code><a href="ytdopy.qmd">ytdopy()</a></code></dt>
<dd>Current period year-to-date compared to full previous period</dd>
</dl>

